### ISSUE TITLE
What's next after cmake install process?

### ISSUE THREAD

**Issue by MikHaiLz69** [AcademySoftwareFoundation/OpenRV#19]
Sorry everyone for a silly question, But I'm a fresh of code compile process.
At first I already got a build with a command below

`cmake --install cmake-build --config Release`

Also, after looking around in the target folder, I couldn't figure out how to run the open RV.
I have included folder structure that was created after the build for you to see. Please explain the next step to me.

Best

![open-rv](https://user-images.githubusercontent.com/42891902/213863753-853f7525-8e4a-4eff-9105-0ba95da10c40.jpg)

**Comment by marcomeyerVFX** [comment]
in the bin directory should be a `rv.exe` which you can run

**Comment by MikHaiLz69** [comment]
> in the bin directory should be a `rv.exe` (I guess, I'm not on Windows) which you can run

Thanks @marcomeyerVFX about the reply 😃 
I though the same as you but when I didn't find rv.exe or something might be related in the bin folder.
I sorted with executable file above the red line and attached the image to show you. 

![open-rv2](https://user-images.githubusercontent.com/42891902/213866028-e954db32-9583-4b67-a853-b3229d1b8f7d.jpg)

**Comment by RichardFrangenberg** [comment]
@MikHaiLz69 That means there were some errors during the build process. Unfortunately the build process doesn't stop then so it might be not obvious that there was an error.
You can write the whole output of the build process to a log file and then search it for errors: https://github.com/AcademySoftwareFoundation/OpenRV/issues/3#issuecomment-1397178404

**Comment by MikHaiLz69** [comment]
Thanks @RichardFrangenberg , I will check the log and find the error and fix it.

**Comment by BrianHanke** [comment]
I had a similar problem, convo here: https://github.com/AcademySoftwareFoundation/OpenRV/issues/3 

In the end I used an Azure VM to build OpenRV. There was something weird with the settings on my laptop so it was better just to start with a clean system.

**Comment by rogernelson** [comment]
Hi @rajiv-hqvfx.  There are three commands there.  The first one configures cmake, the second one builds the dependencies and the third builds RV.

It looks like the output you pasted is coming from the configure command, which completed successfully.  Were there any errors from either of the two build commands? If the build did not complete successfully, the error is likely within one of these.

Note that if it is easier for you, you can do `source rvcmds.sh` from the root folder, followed by `rvmk` to do it all for you automatically (please ensure the paths that are printed in the shell from the source command are correct before doing `rvmk`).

**Comment by rajiv-hqvfx** [comment]
I don't have JOM installed in my pc. Is this mandatory for build?
I found this build error:
  
jom: C:\openrv\OpenRV\cmake-build\_deps\rv_deps_pyside2-src\pyside3_build\py3.9-qt5.15.2-64bit-release\shiboken2\Makefile [all] Error 2
CUSTOMBUILD : error : Error compiling shiboken2 [C:\openrv\OpenRV\cmake-build\cmake\dependencies\RV_DEPS_PYTHON3-stage-target.vcxproj]
  Traceback (most recent call last):
    File "C:\openrv\OpenRV\cmake-build\_deps\rv_deps_pyside2-src\setup.py", line 296, in <module>
      setup_runner.run_setup()
    File "C:\openrv\OpenRV\cmake-build\_deps\rv_deps_pyside2-src\build_scripts\setup_runner.py", line 168, in run_setup
      raise RuntimeError(msg)
  RuntimeError:
  setup.py invocation failed with exit code: 1.
