### ISSUE TITLE
Failed building PySide2 on Linux: no designer file 

### ISSUE THREAD

**Issue by johhnry** [AcademySoftwareFoundation/OpenRV#36]
Hi,

The build fails on Gentoo Linux when building PySide2 with the downloaded Python 3.9:

```
Copying file /usr/lib64/libQt5WaylandCompositor.so.5 to /media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build/lib.linux-x86_64-cpython-39/PySide2/Qt/lib/libQt5WaylandCompositor.so.5.
Copying file /usr/lib64/libicutu.so.72 to /media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build/lib.linux-x86_64-cpython-39/PySide2/Qt/lib/libicutu.so.72.
Traceback (most recent call last):
  File "/home/johhnry/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/setup.py", line 296, in <module>
    setup_runner.run_setup()
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/setup_runner.py", line 125, in run_setup
    self.run_setuptools_setup()
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/setup_runner.py", line 182, in run_setuptools_setup
    setup(**kwargs)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/main.py", line 406, in run
    _install.run(self)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/command/install.py", line 72, in run
    orig.install.run(self)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
    self.run_command('build')
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/main.py", line 638, in run
    self.prepare_packages()
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/main.py", line 1007, in prepare_packages
    return prepare_packages_posix(self, vars)
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/platforms/unix.py", line 218, in prepare_packages_posix
    prepare_standalone_package_linux(self, vars)
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/platforms/linux.py", line 95, in prepare_standalone_package_linux
    rpaths = linux_get_rpaths(designer_path)
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/utils.py", line 979, in linux_get_rpaths
    lines = linux_run_read_elf(executable_path)
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/utils.py", line 940, in linux_run_read_elf
    raise RuntimeError("Running `readelf -d {}` failed with error "
RuntimeError: Running `readelf -d /media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build/lib.linux-x86_64-cpython-39/PySide2/designer` failed with error output:
 readelf: Error: '/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build/lib.linux-x86_64-cpython-39/PySide2/designer': No such file. 
Traceback (most recent call last):
  File "/home/johhnry/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/setup.py", line 296, in <module>
    setup_runner.run_setup()
  File "/media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/build_scripts/setup_runner.py", line 168, in run_setup
    raise RuntimeError(msg)
RuntimeError: 
setup.py invocation failed with exit code: 1.
-64bit-release/pyside2/PySide2/QtWidgets.pyi to /media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_py
side2-src/build/lib.linux-x86_64-cpython-39/PySide2/QtWidgets.pyi.
setup.py invocation was: /home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/bin/python3.9 /home/johhnry/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/setup.py install --qmake=/usr/lib64/qt5/bin/qmake --ignore-git --standalone --openssl=/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_OPENSSL/install/bin --verbose-build --parallel=16 --internal-build-type=pyside2
Copying tree /media/hdd/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/env3_build/py3.9-qt5.15.8
Traceback (most recent call last):
  File "/home/johhnry/git/johhnry/OpenRV/src/build/make_pyside.py", line 284, in <module>
    build()
  File "/home/johhnry/git/johhnry/OpenRV/src/build/make_pyside.py", line 203, in build
    subprocess.run(pyside_build_args).check_returncode()
  File "/usr/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_PYTHON3/install/bin/python3.9', '-s', '-E', '/home/johhnry/git/johhnry/OpenRV/build/_deps/rv_deps_pyside2-src/setup.py', 'install', '--qmake=/usr/lib64/qt5/bin/qmake', '--ignore-git', '--standalone', '--openssl=/home/johhnry/git/johhnry/OpenRV/build/RV_DEPS_OPENSSL/install/bin', '--verbose-build', '--parallel=16']' returned non-zero exit status 1.
```

It seems that it can't find and copy a file called `designer` in the `_deps/rv_deps_pyside2-src/build/lib.linux-x86_64-cpython-39/PySide2` directory.

Do someone know where it comes from?

Thanks!

- OS: `Gentoo 5.15.80-gentoo-x86_64`
- Qt: `5.15.8`

**Comment by rogernelson** [comment]
Hi @johhnry I think you're the first to attempt building with Gentoo.  That file should have been put there when PySide was built.  Is there perhaps an error from earlier in the build when PySide was being built?

**Comment by geffrak** [comment]
designer is a tool that is provided by QT's online installer. I had a similar issue trying to use Qt from homebrew to build OpenRV on a Mac.
