### ISSUE TITLE
error : Option --jobs can only be used with 'jom' on Windows

### ISSUE THREAD

**Issue by jonassorgenfrei** [AcademySoftwareFoundation/OpenRV#47]
I'm getting the followin error building the code:
```
  freetype.vcxproj -> D:\Documents\Development\OpenRV\cmake-build\stage\app\lib\freetype.lib
  Requirement already satisfied: numpy<1.23 in d:\documents\development\openrv\cmake-build\rv_deps_python3\install\lib\site-packages (1.22.4)

  [notice] A new release of pip available: 22.3.1 -> 23.0
  [notice] To update, run: D:\Documents\Development\OpenRV\cmake-build\RV_DEPS_PYTHON3\install\bin\python.exe -m pip install --upgrade pip
  running install
  D:\Documents\Development\OpenRV\cmake-build\RV_DEPS_PYTHON3\install\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  Python architecture is 64bit
  nmake was found in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe
CUSTOMBUILD : error : Option --jobs can only be used with 'jom' on Windows. [D:\Documents\Development\OpenRV\cmake-build\cmake\dependencies\RV_DEPS_PYTHON3-stage-target.vcxproj]
  Traceback (most recent call last):
    File "D:\Documents\Development\OpenRV\cmake-build\_deps\rv_deps_pyside2-src\setup.py", line 296, in <module>
      setup_runner.run_setup()
    File "D:\Documents\Development\OpenRV\cmake-build\_deps\rv_deps_pyside2-src\build_scripts\setup_runner.py", line 168, in run_setup
      raise RuntimeError(msg)
  RuntimeError:
  setup.py invocation failed with exit code: 1.


  setup.py invocation was: D:\Documents\Development\OpenRV\cmake-build\RV_DEPS_PYTHON3\install\bin\python.exe D:/Documents/Development/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/setup.py install --qmake=D:/Bibliotheken/Qt/5.15.2/msvc2019_64/bin/qmake.exe --ignore-git --standalone --openssl=D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_OPENSSL/install/bin --verbose-build --par
  allel=32 --internal-build-type=shiboken2

  Namespace(prepare=True, build=True, source=WindowsPath('D:/Documents/Development/OpenRV/cmake-build/_deps/rv_deps_pyside2-src'), python=WindowsPath('D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install'), qt=WindowsPath('D:/Bibliotheken/Qt/5.15.2/msvc2019_64'), openssl=WindowsPath('D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_OPENSSL/install'), temp=WindowsPat
  h('D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/build'), output=WindowsPath('D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install'), variant='Release')
  Verifying D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/build/libclang.7z
  PATH=D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_OPENSSL/install/bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86;;C:\P
  rogram Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\ide;C:\Program Files (x86)\HTML Help Workshop;;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.
  0.30319\;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\;;D:\msys64\mingw64\bin;D:\msys64\usr\local\bin;D:\msys64\usr\bin;D:\msys64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\msys64\usr\bi
  n\site_perl;D:\msys64\usr\bin\vendor_perl;D:\msys64\usr\bin\core_perl;;D:\msys64\mingw64\bin\
  Found python interpreters ['D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.exe', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.pdb', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.dll', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.exe', 'D:/Documen
  ts/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.exp', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.lib', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.pdb', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python39.dll', 'D:/Documents/Development/OpenRV/cmake-build/R
  V_DEPS_PYTHON3/install/bin/python39.exp', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python39.lib', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python39.pdb', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3stub.exp', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/py
  thon3stub.lib', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/pythonw.exe', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/pythonw.pdb']
  Installing numpy with ['D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.exe', '-s', '-E', '-m', 'pip', 'install', 'numpy<1.23']
  Traceback (most recent call last):
    File "D:\Documents\Development\OpenRV\src\build\make_pyside.py", line 284, in <module>
  Found python interpreters ['D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.exe', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.pdb', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.dll', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.exe', 'D:/Documen
  ts/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.exp', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.lib', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.pdb', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python39.dll', 'D:/Documents/Development/OpenRV/cmake-build/R
  V_DEPS_PYTHON3/install/bin/python39.exp', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python39.lib', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python39.pdb', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3stub.exp', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/py
  thon3stub.lib', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/pythonw.exe', 'D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/pythonw.pdb']
  Found MSVC compiler environment init script (vcvars64.bat):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvars64.bat
  Could not find jom.exe at the expected location: D:/Bibliotheken/Qt/Tools/QtCreator/bin/jom
  Build performance might be impacted
  Executing ['D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.exe', '-s', '-E', 'D:/Documents/Development/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/setup.py', 'install', '--qmake=D:/Bibliotheken/Qt/5.15.2/msvc2019_64/bin/qmake.exe', '--ignore-git', '--standalone', '--openssl=D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_OPENSSL/install/bin', '-
  -verbose-build', '--parallel=32']
      build()
    File "D:\Documents\Development\OpenRV\src\build\make_pyside.py", line 203, in build
      subprocess.run(pyside_build_args).check_returncode()
    File "D:/msys64/mingw64/lib/python3.10/subprocess.py", line 457, in check_returncode
      raise CalledProcessError(self.returncode, self.args, self.stdout,
  subprocess.CalledProcessError: Command '['D:/Documents/Development/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python.exe', '-s', '-E', 'D:/Documents/Development/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/setup.py', 'install', '--qmake=D:/Bibliotheken/Qt/5.15.2/msvc2019_64/bin/qmake.exe', '--ignore-git', '--standalone', '--openssl=D:/Documents/Development/OpenRV/cmake-build/RV
  _DEPS_OPENSSL/install/bin', '--verbose-build', '--parallel=32']' returned non-zero exit status 1.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\Documents\Development\OpenRV\cmake-build\CMakeFiles\cdf2ee0f297c16c94fa80d00cbed2c6e\RV_DEPS_PYSIDE2-build-flag.rule;D:\Documents\Development\OpenRV\cmake-build\CMakeFiles\e06857a341b9e7517a351ea5d7343c48\python39.dll.rule;D:\
Documents\Development\OpenRV\cmake-build\CMakeFiles\aaf9480ae0c40501b64285f8479037e8\RV_DEPS_PYTHON3-stage-target.rule' exited with code 1. [D:\Documents\Development\OpenRV\cmake-build\cmake\dependencies\RV_DEPS_PYTHON3-stage-target.vcxproj]
  TwkMath.vcxproj -> D:\Documents\Development\OpenRV\cmake-build\stage\app\lib\TwkMath.lib
```

Sounds to me like there's an issue with jom, but i installed jom at: 
D:\Bibliotheken\Qt\Tools\QtCreator\bin\jom.exe

I ran the following commands: 
```
cmake -B cmake-build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DRV_DEPS_WIN_PERL_ROOT=/c/Strawberry/perl/bin -DRV_DEPS_QT5_LOCATION=/d/Bibliotheken/Qt/5.15.2/msvc2019_64

cmake --build cmake-build --config Release --target rv -j8
````

Any idea what might be the issue here?

I 'm on windows 10, i have Visual Studio 2017 and 2019 installed and no wsl and no vs2022

**Comment by jonassorgenfrei** [comment]
Hi @rogernelson 
thank you so much that fixed the issue. Tought the path Tools\QtCreator\bin\jom was describing the jom file. 

After fixing this problem i ran into the path length issue described in the docs and after another hour of compiling i ran into the alocal issue described in  #3 so i needed to export ACLOCAL_PATH=/usr/share/aclocal.
May be all these issue should be added to the windows build instructions? So other people don't run into these issues again. 

But thanks for the help, this fixes all my problems : )

**Comment by geffrak** [comment]
Closing it because all your problems are fixed. We will try to do something about all the windows build issues.

Feel free to re-open if required.

**Comment by rogernelson** [comment]
Sorry for all the hassle getting it to build.  We know the Windows build process could use some love; like Kerby said, we're working on it.

**Comment by jonassorgenfrei** [comment]
Thanks yeah this fixes all the problems and builds sucessfully. 

Yeah just wanted to point out which where the issues if anyone else gets stuck at this point. 
If you like i can add this info to the windows build infos and create a PR?

**Comment by jonassorgenfrei** [comment]
Btw i just saw that the jom location is hardcoded in: 
OpenRV\src\build\make_pyside.py l.188     os.path.join(QT_OUTPUT_DIR, "..", "..", "Tools", "QtCreator", "bin", "jom")
but as far as i know the jom.exe should be in bin. 
Does it make sense to fix this and create a PR for this or is there any reason it should be in bin/jom ?
